accounts/urls.py
from django.urls import path
from . import views

app_name = 'accounts'
urlpatterns = [
    path('', views.index, name='index'),
    path('signup/', views.signup, name='signup'),
    path('login/', views.login, name='login'),
    path('logout/', views.logout, name='logout'),
    path('<int:persons_pk>', views.profile, name='profile'),
]

movies/urls.py
from django.urls import path
from . import views

app_name = 'movies'
urlpatterns = [
    path('', views.index, name='index'),
    path('<int:movie_pk>/', views.detail, name='detail'),
    path('<int:movie_pk>/reviews/new/', views.review_create, name='review_create'),
    path('<int:movie_pk>/reviews/delete/<int:review_pk>', views.review_delete, name='review_delete'),
    path('<int:movie_pk>/like/', views.like, name='like'),
]

pjt10/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('accounts/', include('accounts.urls')),
    path('movies/', include('movies.urls')),
    path('admin/', admin.site.urls),
]

accounts/models.py
from django.db import models
from django.conf import settings
from django.contrib.auth.models import AbstractUser

# Create your models here.
class User(AbstractUser):
    followers = models.ManyToManyField(settings.AUTH_USER_MODEL, related_name='followings')

movies/models.py
from django.db import models
from django.conf import settings

# Create your models here.
class Genre(models.Model):
    name = models.CharField(max_length=20)

    def __str__(self):
        return self.name
    

class Movie(models.Model):
    title = models.CharField(max_length=30)
    audience = models.IntegerField()
    poster_url = models.CharField(max_length=140)
    description = models.TextField()
    like_users = models.ManyToManyField(settings.AUTH_USER_MODEL, related_name='like_movies', blank=True)
    genres = models.ManyToManyField(Genre, blank=True)

    def __str__(self):
        return self.title


class Review(models.Model):
    content = models.CharField(max_length=140)
    score = models.IntegerField()
    user = models.ForeignKey(settings.AUTH_USER_MODEL, on_delete=models.CASCADE)
    movie = models.ForeignKey(Movie, on_delete=models.CASCADE)

    class Meta:
        ordering = ('-pk',)
    
    def __str__(self):
        return self.content
    

accounts/forms.py
from django.contrib.auth.forms import UserChangeForm, UserCreationForm
from django.contrib.auth import get_user_model

class CustomUserCreationForm(UserCreationForm):
    class Meta(UserCreationForm.Meta):
        model = get_user_model()
        fields = UserCreationForm.Meta.fields

movies/forms.py
from django import forms
from .models import Review

class ReviewForm(forms.ModelForm):
    content = forms.CharField(
        label='리뷰 작성',
        max_length='140'
    )
    score = forms.IntegerField(max_value=10, min_value=0)

    class Meta:
        model = Review
        fields = ('content', 'score',)

accounts/views.py
from django.contrib.auth import get_user_model
from django.contrib.auth.models import User
from django.contrib.auth.decorators import login_required
from django.views.decorators.http import require_POST
from django.contrib.auth import login as auth_login, logout as auth_logout, update_session_auth_hash
from django.shortcuts import render, redirect, get_object_or_404
from django.contrib.auth.forms import AuthenticationForm
from .forms import  CustomUserCreationForm

# Create your views here.

def index(request):
    user = get_user_model()
    persons = user.objects.all()
    context = {'persons':persons,}
    return render(request, 'accounts/index.html', context)


def signup(request):
    if request.user.is_authenticated:
        return redirect('movies:index')
    if request.method == 'POST':
        form = CustomUserCreationForm(request.POST)
        if form.is_valid():
            user = form.save()
            auth_login(request, user)
            return redirect('movies:index')

    else:
        form = CustomUserCreationForm()
    context = {'form':form,}
    return render(request, 'accounts/auth_form.html', context)

def login(request):
    if request.user.is_authenticated:
        return redirect('movies:index')

    if request.method == 'POST':
        form = AuthenticationForm(request, request.POST)
        if form.is_valid():
            auth_login(request, form.get_user())
            return redirect(request.GET.get('next') or 'movies:index')

    else:
        form = AuthenticationForm()
    context = {'form':form,}
    return render(request, 'accounts/login.html', context)

def logout(request):
    auth_logout(request)
    return redirect('movies:index')


def profile(request, persons_pk):
    persons = get_object_or_404(get_user_model(), pk=persons_pk)
    context = {'persons':persons,}
    return render(request, 'accounts/profile.html', context)

movies/views.py
from django.contrib.auth import get_user_model
from django.shortcuts import render, redirect, get_object_or_404
from django.views.decorators.http import require_POST
from django.contrib.auth.decorators import login_required
from .models import Movie, Review
from .forms import ReviewForm
# Create your views here.
def index(request):
    movies = Movie.objects.all()
    context = {'movies': movies, }
    return render(request, 'movies/index.html', context)


def detail(request, movie_pk):
    movie = get_object_or_404(Movie, pk=movie_pk)
    reviews = movie.review_set.all()
    review_form = ReviewForm()
    context = {
        'movie': movie,
        'reviews': reviews,
        'review_form': review_form,
    }
    return render(request, 'movies/detail.html', context)


@require_POST
def review_create(request, movie_pk):
    if request.user.is_authenticated:
        form = ReviewForm(request.POST)
        if form.is_valid():
            review = form.save(commit=False)
            review.movie_id = movie_pk
            review.user = request.user
            review.save()
    return redirect('movies:detail', movie_pk)


@require_POST
def review_delete(request, movie_pk, review_pk):
    if request.user.is_authenticated:
        review = get_object_or_404(Review, pk=review_pk)
        if request.user == review.user:
            review.delete()
        return redirect('movies:detail', movie_pk)


@login_required
def like(request, movie_pk):
    movie = get_object_or_404(Movie, pk=movie_pk)
    if movie.like_users.filter(pk=request.user.pk).exists():
        movie.like_users.remove(request.user)
    else:
        movie.like_users.add(request.user)
    return redirect('movies:index')

accounts/templates/accounts/auth_form.html
{% extends 'movies/base.html' %}
{% load bootstrap4 %}

{% block content %}
{% if request.resolver_match.url_name == 'signup' %}
<h1>회원가입</h1>
{% elif request.resolver_match.url_name == 'login' %}
<h1>로그인</h1>
{% endif %}

<form action="" method="POST">
{% csrf_token %}
{% bootstrap_form form layout="horizontal"%}
  {% buttons submit="회원가입" reset="Cancel" %}{% endbuttons %}
</form>
{% endblock  %}

accounts/templates/accounts/index.html
{% extends 'movies/base.html' %}
{% block title %}ACCOUNTS{% endblock title %}

{% block content %}
<h1 class="text-center">전체 사용자 목록</h1>
<div class="col-6 mx-auto mt-3">
  {% for person in persons %}
  <ul><a href="{% url 'accounts:profile' person.pk %}">{{ person.username }}</a></ul>
  <hr>
  {% endfor %}
</div>
{% endblock  %}

accounts/templates/accounts/login.html
{% extends 'movies/base.html' %}
{% load bootstrap4 %}

{% block content %}
<h1>Log in </h1>
<form action="" method="POST">
{% csrf_token %}
{% bootstrap_form form layout="horizontal"%}
  {% buttons submit="로그인" reset="Cancel" %}{% endbuttons %}
</form>
{% endblock  %}

accounts/templates/accounts/profile.html
{% extends 'movies/base.html' %}

{% block title %}{{ persons.username }}'s Profile{% endblock title %}

{% block content %}
<h1 class="text-center">{{ persons.username }}'s Profile</h1>
{% with  followings=person.followings.all followers=person.followers.all  %}
<p class="text-center">팔로잉 : {{ followings|length }} | 팔로워 : {{ followers|length }}</p>
{% endwith %}
<hr>

<h3 class="text-center">{{ persons.username }} 이/가 좋아하는 영화</h3>
{% with movies=persons.like_movies.all %}
<div class="col-4 my-2">
  {% for movie in movies %}
  <div class="card">
    <div class="card-body">
      <h5 class="card-title"> {{ movie.title }} </h5>
      <p class="card-text">{{ movie.review_set.all|length }}개의 리뷰</p>
    </div>
  </div>
  {% endfor %}

  {% endwith %}

</div>
</div>
<hr>
  <h3 class="text-center mt-5 mb-3">{{ persons.username }} 이/가 작성한 리뷰</h3>
  <div class="row">
    {% with reviews=persons.review_set.all %}
      {% for review in reviews %}
        <div class="col-4 my-2">
          <div class="card mb-3">
            <div class="card-body">
              <blockquote class="blockquote mb-0">
                <p>영화: {{ review.movie.title }}</p>
                <p>평점: {{ review.score }}</p>
                <p>내용: {{ review.content }}</p>
              </blockquote>
            </div>
          </div>
        </div>
      {% empty %}
        <div class="col-4 my-2">
          <div class="card mb-3">      
            <div class="card-body">
              <p class="card-text"><b>{{ persons.username }} 이/가 작성한 리뷰가 없습니다.</b></p>
            </div>
          </div>
        </div>
      {% endfor %}
    {% endwith %}
  </div>
{% endblock  %}

accounts/templates/accounts/signup.html
{% extends 'movies/base.html' %}
{% load bootstrap4 %}

{% block content %}
<h1>Sign up</h1>
<form action="" method="POST">
{% csrf_token %}
{% bootstrap_form form layout="horizontal"%}
  {% buttons submit="회원가입" reset="Cancel" %}{% endbuttons %}
</form>
{% endblock  %}

movies/templates/movies/_movie.html
{% load bootstrap4 %}
<div class="col-3 my-3">
  <a href="{% url 'movies:detail' movie.pk %}">
    <img src="{{ movie.poster_url }}" class="img-fluid" alt="{{ movie.title }}">
  </a>
    <p class="text-center">
      <a href="{% url 'movies:like' movie.pk %}">
        {% if user in movie.like_users.all %}
          <i class="fas fa-heart fa-lg" style="color: crimson;"></i>
        {% else %}
          <i class="fas fa-heart fa-lg" style="color: black;"></i>
        {% endif %}
      </a>
      <b>{{ movie.like_users.all|length }} 명이 이 영화를 좋아합니다.</b>
    </p>
</div>

movies/templates/movies/_nav.html
<nav class="navbar navbar-expand-lg navbar-dark bg-dark mb-3">
  {% if user.is_authenticated %}
  <!-- request.user.is_authenticated 의 축약; 둘 다 같은 것 -->
  <a class="navbar-brand" href="{% url 'movies:index' %}">
    Hello! {{ user.username }} !
  </a>
  <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarNav" aria-controls="navbarNav"
    aria-expanded="false" aria-label="Toggle navigation">
    <span class="navbar-toggler-icon"></span>
  </button>
  <div class="collapse navbar-collapse justify-content-end" id="navbarNav">
    <ul class="navbar-nav">
      <li class="nav-item">
        <a class="nav-link" href="{% url 'accounts:profile' user.pk %}">내 프로필</a>
      </li>
      <li class="nav-item">
        <a class="nav-link" href="{% url 'accounts:logout' %}">로그아웃</a>
      </li>
    </ul>
  </div>

{% else %}
  <a class="navbar-brand" href="{% url 'movies:index' %}">
    Hello! STRANGER !
  </a>
  <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarNav" aria-controls="navbarNav"
    aria-expanded="false" aria-label="Toggle navigation">
    <span class="navbar-toggler-icon"></span>
  </button>
  <div class="collapse navbar-collapse justify-content-end" id="navbarNav">
    <ul class="navbar-nav">
      <li class="nav-item">
        <a class="nav-link" href="{% url 'accounts:login' %}">로그인</a>
      </li>
      <li class="nav-item">
        <a class="nav-link" href="{% url 'accounts:signup' %}">회원가입</a>
      </li>
    </ul>
  </div>
{% endif %}
</nav>

movies/templates/movies/base.html
{% load bootstrap4 %}

<!DOCTYPE html>
<html lang="ko">
<head>
  <meta charset="UTF-8">
  <meta name="viewport" content="width=device-width, initial-scale=1.0">
  <meta http-equiv="X-UA-Compatible" content="ie=edge">
  <title>{% block title %}{% endblock title %}</title>
  <script src="https://kit.fontawesome.com/8fb1a5fc3b.js" crossorigin="anonymous"></script>
  {% bootstrap_css %}
</head>
<body>
  {% include 'movies/_nav.html' %}

  <div class="container">
    {% block content %}
    {% endblock %}
  </div>
  
  {% bootstrap_javascript jquery='full' %}
</body>
</html>

movies/templates/movies/detail.html
{% extends './base.html' %}
{% load bootstrap4 %}

{% block title %}{{ movie.title }}{% endblock title %}

{% block content %}
<div class="card mx-auto" style="width: 36rem;">
  <div class="card-body">
    <h5 class="card-title text-center">{{ movie.title }}</h5>
    <p class="card-text">누적관객수: {{ movie.audience }}</p>
    <p class="card-text">{{ movie.description }}</p>
  </div>
  <img class="card-img-bottom" src="{{ movie.poster_url }}/100px180/" alt="{{ movie.title }}">
</div>

<!-- 리뷰 보이는 곳 -->
<div class="col-6 mx-auto">
<hr>
{% for review in reviews %}
<div class="list-group">
  {% if not user.is_authenticated %}
  <li class="list-group-item list-group-item-action">{{ forloop.revcounter }}: {{ review.content }} | 작성:
    {{ review.user }}</li>
  {% else %}
  <form action="{% url 'movies:review_delete' movie.pk review.pk %}" method="POST">
    {% csrf_token %}
    {% if request.user == review.user %}
    <input type="submit" class="list-group-item list-group-item-action"
      value="{{ forloop.revcounter }}: {{ review.content }} | 평점: {{ review.score }} || 작성: {{ review.user }}">
    {% else %}
    <input type="submit" class="list-group-item list-group-item-action"
      value="{{ forloop.revcounter }}: {{ review.content }} | 평점: {{ review.score }} || 작성: {{ review.user }}">
    {% endif %}
  </form>
  {% endif %}
</div>
{% empty %}
<p><b>입력된 리뷰가 없습니다.</b></p>
{% endfor %}
<hr>
<!-- 댓글 작성 공간(form) -->
{% if user.is_authenticated  %}
<form action="{% url 'movies:review_create' movie.pk %}" method="POST">
  {% csrf_token %}
  {% bootstrap_form review_form %}
  <input class="btn btn-secondary" type="submit" value="리뷰 추가">
</form>
<hr>
{% else %}
<a class="btn btn-warning" href="{% url 'accounts:login' %}">리뷰를 작성하려면 로그인하세요.</a>
<hr>
{% endif %}
<a class="btn btn-primary" href="{% url 'movies:index' %}">BACK</a>
</div>
{% endblock  %}

movies/templates/movies/index.html
{% extends './base.html' %}

{% block title %}MOVIES{% endblock title %}

{% block content %}
  <h1 class="text-center">MOVIES</h1>
  <div class="container">
    <div class="row">
      {% for movie in movies %}
        {% include 'movies/_movie.html' %}
      {% endfor %}
    </div>
  </div>
{% endblock %}